Hue_low : 15
Hue_high : 37
Saturation_low : 114
Saturation_high : 199
Value_low : 114
Value_high : 200
gray_thresh : 0
number_of_lines : 85
error_threshold : 0.51
Width_min : 0
Width_max : 437
inverted_filter : 0
camera_start_height : 312
camera_bottom_height : 630
camera_left_width : 160
camera_right_width : 640
steering_sensitivity : 1.0
zero_throttle : 0.01
no_error_throttle : 0.40
error_throttle : 0.20
