Hue_low : 73
Hue_high : 135
Saturation_low : 72
Saturation_high : 255
Value_low : 124
Value_high : 255
gray_thresh : 20
number_of_lines : 100
error_threshold : 0.18
Width_min : 10
Width_max : 500
inverted_filter : 0
camera_start_height : 32
camera_bottom_height : 92
camera_left_width : 0
camera_right_width : 160
steering_sensitivity : 1.0
no_error_throttle : -0.018
error_throttle : -0.018
zero_throttle : -0.018
error_threshold : 0.18
