Hue_low : 71
Hue_high : 122
Saturation_low : 97
Saturation_high : 255
Value_low : 66
Value_high : 255
gray_thresh : 0
number_of_lines : 16
error_threshold : 0.14
Width_min : 24
Width_max : 121
inverted_filter : 0
camera_start_height : 180
camera_bottom_height : 360
camera_left_width : 0
camera_right_width : 640
steering_sensitivity : 1.0
zero_throttle : 0.10299999999999998
no_error_throttle : 0.09099999999999997
error_throttle : 0.09099999999999997
