Hue_low : 15
Hue_high : 44
Saturation_low : 95
Saturation_high : 196
Value_low : 117
Value_high : 209
gray_thresh : 48
number_of_lines : 99
error_threshold : 0.49
Width_min : 151
Width_max : 333
inverted_filter : 0
camera_start_height : 306
camera_bottom_height : 600
camera_left_width : 79
camera_right_width : 720
steering_sensitivity : 0.4
zero_throttle : 0.10000000000000009
no_error_throttle : 0.13900000000000005
error_throttle : 0.6900000000000005
