Hue_low : 14
Hue_high : 49
Saturation_low : 49
Saturation_high : 194
Value_low : 113
Value_high : 203
gray_thresh : 0
number_of_lines : 85
error_threshold : 0.51
Width_min : 0
Width_max : 437
inverted_filter : 0
camera_start_height : 366
camera_bottom_height : 864
camera_left_width : 160
camera_right_width : 640
steering_sensitivity : 0.6
zero_throttle : 0.069999999999997
no_error_throttle : 0.099999999994
error_throttle : 0.08500000000000013
