Hue_low : 0 
Hue_high : 92 
Saturation_low : 0 
Saturation_high : 134 
Value_low : 0 
Value_high : 132 
gray_thresh : 172 
number_of_lines : 100 
error_threshold : 0.14 
Width_min : 10 
Width_max : 500 
inverted_filter : 1 
camera_start_height : 312 
camera_bottom_height : 612 
camera_left_width : 0 
camera_right_width : 800 
steering_sensitivity : 1.0 
zero_throttle : 0.13400000000000012 
no_error_throttle : 0.13800000000000012 
error_throttle : 0.15000000000000013 
