Hue_low : 1
Hue_high : 28
Saturation_low : 44
Saturation_high : 172
Value_low : 206
Value_high : 255
gray_thresh : 0
number_of_lines : 100
error_threshold : 0.14
Width_min : 27
Width_max : 105
inverted_filter : 0
camera_start_height : 300
camera_bottom_height : 600
camera_left_width : 0
camera_right_width : 800
steering_sensitivity : 0.45
zero_throttle : 0.124
no_error_throttle : 0.146
error_throttle : 0.14
