Hue_low : 15
Hue_high : 44
Saturation_low : 95
Saturation_high : 196
Value_low : 117
Value_high : 209
gray_thresh : 48
number_of_lines : 99
error_threshold : 0.49
Width_min : 151
Width_max : 333
inverted_filter : 0
camera_start_height : 366
camera_bottom_height : 864
camera_left_width : 160
camera_right_width : 640
steering_sensitivity : 0.6
zero_throttle : 0.127
no_error_throttle : 0.158
error_throttle : 0.142
