Hue_low : 15
Hue_high : 53
Saturation_low : 68
Saturation_high : 221
Value_low : 155
Value_high : 231
gray_thresh : 0
number_of_lines : 100
error_threshold : 0.14
Width_min : 27
Width_max : 105
inverted_filter : 0
camera_start_height : 300
camera_bottom_height : 600
camera_left_width : 0
camera_right_width : 800
steering_sensitivity : 0.45
zero_throttle : 0.127
no_error_throttle : 0.158
error_throttle : 0.142
